### ISSUE TITLE
class loading fails

### ISSUE THREAD

**Issue by koshilife** [koshilife/timetree-api-ruby-client#29]
When calling `client.current_user`

```ruby
$ irb
>> require 'timetree'
=> true
>> client = TimeTree::Client.new '<TOKEN>'
=> #<TimeTree::Client:70327557260660>
>> client.current_user
Traceback (most recent call last):
        4: from console.rb:6:in `<main>'
        3: from (irb):4
        2: from ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/timetree-0.3.1/lib/timetree/client.rb:33:in `current_user'
        1: from ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/timetree-0.3.1/lib/timetree/client.rb:288:in `to_model'
NameError (uninitialized constant TimeTree::BaseModel)
```

There is something wrong zeitwerk settings.

**Comment by koshilife** [comment]
I released fixed version `0.3.2`.
